### ISSUE TITLE
Make it accessible from build.zig (like Snektron/vulkan-zig)

### ISSUE THREAD

**Issue by terraquad** [MasterQ32/zig-opengl#15]
Basically add some type of API for Zig's build system to generate the code from the build script so the bindings are accessible from everywhere in the code.

**Comment by ikskuh** [comment]
I will not do that as `OpenGL-Registry/xml/gl.xml` alone is 3MB large, while all APIs generated by this tool by default in the CI in total are 8MB in total, while the largest generated API is 500K large.

This means that each revision of this package would add 3MB of disk storage to the package cache, while just checking in a generated file will add something between 100K and 500K of size.

Can you explain your use case, maybe we can make that easier for you in other means?

**Comment by terraquad** [comment]
I want to add this project as a submodule to my repo and then use build.zig to build the API for use. I have done this before with vulkan-zig and it worked fine.

I could use `b.addSystemCommand` to invoke the generator but it's ugly as hell. vulkan-zig provides an API to build.zig so that I can generate the code from there.

**Comment by ikskuh** [comment]
I mean, you can do that, but you have to download the generator as a binary for your platform anyways, then you can just vendor `gl.xml` and the generator binary instead of adding this as a submodule, or you have to depend on `dotnet` as well.

I don't think it's a good idea to expose this via build.zig, as there is literally no zig code involved in this repository.
